export {default as loginInput} from "./LoginInput"
export {default as MainLoader} from "./MainLoader"
export {default as Alert} from "./Alert"

// export {default as DBLeftSection} from "./DBLeftSection"
// export {default as DBRightSection} from "./DBRightSection"

export { default as Header } from "./Header"
export { default as Home } from "./Home"
export { default as Slider } from "./Slider"
export { default as HomeSlider } from "./HomeSlider"
export { default as SliderCard } from "./SliderCard"
export { default as FilterSection } from "./FilterSection"
export { default as Cart } from "./Cart"
export { default as CheckOutSuccess } from "./CheckOutSuccess"
export { default as OrderData } from "./OrderData"
export { default as Gallery } from "./Gallery"
export { default as Review } from "./Review"
export { default as AboutUs } from "./AboutUs"
export { default as Testimonial } from "./Testimonial"
export { default as Services } from "./Services"
export { default as Footer } from "./Footer"
export { default as UsersOrders } from "./UsersOrders"